### ISSUE TITLE
Add tests and CI

### ISSUE THREAD

**Issue by mikkonie** [bihealth/cubi-isa-templates#2]
Tests should be added along with CI using Github Actions.

- Run cookiecutter on all templates, ensure they build without errors
- Run black check
- Run flake8 check

**Comment by sellth** [comment]
We should make sure to test and validate all variations of cookiecutter multiple choice inputs. Possible approach: Cookiecutter's *extra_content* override parameter.

**Comment by mikkonie** [comment]
Oops, accidentally closed. CI still needs to be added.
