### ISSUE TITLE
Slash characters in investigation title not sanitized for assay file names

### ISSUE THREAD

**Issue by mikkonie** [bihealth/cubi-isa-templates#37]
### Describe the Bug

Something originally noticed in SODAR, see bihealth/sodar-server#1896.

If one or more `/` characters are present in the investigation title, they get carried over to assay file names. This causes an error when Cookiecutter creates a file, as the slash gets intepreted as a path to a folder.

### How to Reproduce

Enter a slash character `/` in the investigation title and try to create the ISA-Tab.

### Expected Behavior

We should replace the slash characters with e.g. underscore when forming the assay file name. When entered into the actual investigation file, these characters should be allowed in the investigation title, as AFAIK they are not forbidden by ISA-Tab.

### Notes

In Unix/Linux, `/` should be the only forbidden ASCII character, so we shouldn't have to worry about other special characters.

**Comment by mikkonie** [comment]
I noticed this does not actually happen consistently with all templates. For `cytof` a slash in investigation title works, because it uses the investigation identifier instead of the investigation title for the file name. A slash in the ID does cause the same error however.

For the stem cell core templates this works, as the use the study title and correctly replace the slash characters.

**Comment by sellth** [comment]
closed via #38
